### ISSUE TITLE
服务器错误500

### ISSUE THREAD

**Issue by zzisk** [ZBrettonYe/ProxyPanel#7]
**描述你遇到的bug**
错误500
**如何复现你的BUG**
宝塔安装
运行php artisan key:generate

In RouteAction.php line 89:

  Invalid route action: [App\Http\Controllers\tiGmHD].

**截图**

![image](https://user-images.githubusercontent.com/28900500/87928957-42b25c80-cab8-11ea-8fdf-cf3061ea6642.png)

**Comment by ZBrettonYe** [comment]
已修复，请更新到最新代码
